// atl-sample.idl : IDL source for atl-sample
//

// This file will be processed by the MIDL tool to
// produce the type library (atlsample.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(4d8fe78f-0fd7-409c-b6c9-20bbc9e103e1),
	version(1.0),
]
library atlsampleLib
{
	importlib("stdole2.tlb");
};

